<a href="https://colab.research.google.com/github/atrikhs/Pytorch/blob/main/Pytorch_multiRegrn1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np
import matplotlib.pyplot as plt
from torch import nn
from sklearn.model_selection import train_test_split
import pandas as pd

In [ ]:
class LinearRegV3(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear_layer1 = nn.Linear(in_features = 3, out_features=1)

  def forward(self, x:torch.Tensor) -> torch.Tensor:
    return self.linear_layer1(x)

In [ ]:
torch.manual_seed(42)
model1 = LinearRegV3()
model1

LinearRegV3(
  (linear_layer1): Linear(in_features=3, out_features=1, bias=True)
)

In [ ]:
model1.state_dict()

OrderedDict([('linear_layer1.weight', tensor([[ 0.4414,  0.4792, -0.1353]])),
             ('linear_layer1.bias', tensor([0.5304]))])

In [ ]:
X1 = np.arange(1, 21, step = 0.02)

In [ ]:
print(len(X1))

1000


In [ ]:
X2 = np.arange(21, 41, step = 0.02)

In [ ]:
print(len(X2))

1000


In [ ]:
X3 = np.arange(41, 61, step = 0.02)

In [ ]:
print(len(X3))

1000


In [ ]:
w1 = 3
w2 = 5
w3 = 14
b = 52

y = w1*X1 + w2*X2 + w3*X3 + b
y


array([ 734.  ,  734.44,  734.88,  735.32,  735.76,  736.2 ,  736.64,
        737.08,  737.52,  737.96,  738.4 ,  738.84,  739.28,  739.72,
        740.16,  740.6 ,  741.04,  741.48,  741.92,  742.36,  742.8 ,
        743.24,  743.68,  744.12,  744.56,  745.  ,  745.44,  745.88,
        746.32,  746.76,  747.2 ,  747.64,  748.08,  748.52,  748.96,
        749.4 ,  749.84,  750.28,  750.72,  751.16,  751.6 ,  752.04,
        752.48,  752.92,  753.36,  753.8 ,  754.24,  754.68,  755.12,
        755.56,  756.  ,  756.44,  756.88,  757.32,  757.76,  758.2 ,
        758.64,  759.08,  759.52,  759.96,  760.4 ,  760.84,  761.28,
        761.72,  762.16,  762.6 ,  763.04,  763.48,  763.92,  764.36,
        764.8 ,  765.24,  765.68,  766.12,  766.56,  767.  ,  767.44,
        767.88,  768.32,  768.76,  769.2 ,  769.64,  770.08,  770.52,
        770.96,  771.4 ,  771.84,  772.28,  772.72,  773.16,  773.6 ,
        774.04,  774.48,  774.92,  775.36,  775.8 ,  776.24,  776.68,
        777.12,  777

In [ ]:
X = pd.DataFrame({'X1': X1, 'X2': X2, 'X3': X3})
X

X1     X2     X3
0     1.00  21.00  41.00
1     1.02  21.02  41.02
2     1.04  21.04  41.04
3     1.06  21.06  41.06
4     1.08  21.08  41.08
..     ...    ...    ...
995  20.90  40.90  60.90
996  20.92  40.92  60.92
997  20.94  40.94  60.94
998  20.96  40.96  60.96
999  20.98  40.98  60.98

[1000 rows x 3 columns]

In [ ]:
len(X), len(y)

(1000, 1000)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [ ]:
len(X_train), len(X_test), len(y_train), len(y_test)

(800, 200, 800, 200)

In [ ]:
X_test

X1     X2     X3
284   6.68  26.68  46.68
956  20.12  40.12  60.12
811  17.22  37.22  57.22
391   8.82  28.82  48.82
295   6.90  26.90  46.90
..     ...    ...    ...
361   8.22  28.22  48.22
954  20.08  40.08  60.08
165   4.30  24.30  44.30
111   3.22  23.22  43.22
243   5.86  25.86  45.86

[200 rows x 3 columns]

In [ ]:
X_train = X_train.to_numpy(dtype = np.float32)
X_train

array([[14.88, 34.88, 54.88],
       [ 2.84, 22.84, 42.84],
       [ 4.12, 24.12, 44.12],
       ...,
       [16.36, 36.36, 56.36],
       [14.26, 34.26, 54.26],
       [ 9.34, 29.34, 49.34]], dtype=float32)

In [ ]:
loss_fn = nn.L1Loss()
optimizer = torch.optim.SGD(params = model1.parameters(), lr = 0.01)

In [ ]:
device  = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [ ]:
model1 = model1.to(device)
next(model1.parameters()).device

device(type='cuda', index=0)

In [ ]:
X_train = torch.from_numpy(X_train).to(device)

In [ ]:
len(X_train)

800

In [ ]:
y_train = y_train.astype(dtype = np.float32)

In [ ]:
len(y_train)

800

In [ ]:
y_train = torch.from_numpy(y_train).to(device)

In [ ]:
epoch = 10000

for i in range(epoch):
  model1.train()

  y_pred_train = model1(X_train)

  loss = loss_fn(y_pred_train, y_train)

  optimizer.zero_grad()

  loss.backward()

  optimizer.step()



In [ ]:
loss

tensor(108.5304, device='cuda:0', grad_fn=<MeanBackward0>)

In [ ]:
model1.state_dict()
# w1 = 3
# w2 = 5
# w3 = 14
# b = 52

OrderedDict([('linear_layer1.weight',
              tensor([[-23.9293,   0.2248,  23.7266]], device='cuda:0')),
             ('linear_layer1.bias', tensor([1.7362], device='cuda:0'))])