<a href="https://colab.research.google.com/github/atrikhs/Pytorch/blob/main/Pytorch_regn22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np
import matplotlib.pyplot as plt
from torch import nn
from sklearn.model_selection import train_test_split
import pandas as pd
from sklearn.preprocessing import StandardScaler

# Define model
class LinearRegV3(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear_layer1 = nn.Linear(in_features=3, out_features=1)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.linear_layer1(x)

# Data generation
# X1 = np.arange(1, 21, step=0.02)
# X2 = np.arange(21, 41, step=0.02)
# X3 = np.arange(41, 61, step=0.02)

np.random.seed(42)
# X1 = np.random.uniform(1, 21, 1000)
# X2 = np.random.uniform(21, 41, 1000)
# X3 = np.random.uniform(41, 61, 1000)

X1 = np.random.randn(10000)
X2 = np.random.randn(10000)
X3 = np.random.randn(10000)


w1, w2, w3, b = 23, 15, 31, 97
y = w1 * X1 + w2 * X2 + w3 * X3 + b
X = pd.DataFrame({'X1': X1, 'X2': X2, 'X3': X3})

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Normalize features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Convert to PyTorch tensors
X_train = torch.from_numpy(X_train.astype(np.float32))
y_train = torch.from_numpy(y_train.astype(np.float32)).unsqueeze(1)  # add dimension

device = 'cuda' if torch.cuda.is_available() else 'cpu'

# Model setup
torch.manual_seed(42)
model1 = LinearRegV3().to(device)
loss_fn = nn.MSELoss()
optimizer = torch.optim.SGD(model1.parameters(), lr=0.01)

# Move data to device
X_train = X_train.to(device)
y_train = y_train.to(device)

In [ ]:
# Training loop
epochs = 3000
for i in range(epochs):
    model1.train()
    y_pred_train = model1(X_train)
    loss = loss_fn(y_pred_train, y_train)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if i % 1000 == 0:
        print(f"Epoch {i}: Loss = {loss.item():.4f}")

# Check learned parameters
print("Learned weights and bias:", list(model1.parameters()))


Epoch 0: Loss = 11040.4385
Epoch 1000: Loss = 0.0000
Epoch 2000: Loss = 0.0000
Learned weights and bias: [Parameter containing:
tensor([[23.0884, 15.0271, 30.6058]], device='cuda:0', requires_grad=True), Parameter containing:
tensor([97.0644], device='cuda:0', requires_grad=True)]


In [ ]:
model1.state_dict()

OrderedDict([('linear_layer1.weight',
              tensor([[23.0884, 15.0271, 30.6058]], device='cuda:0')),
             ('linear_layer1.bias', tensor([97.0644], device='cuda:0'))])

In [ ]:
w1, w2, w3, b = 23, 15, 31, 97


In [ ]:
X1 = np.random.randn(1000)

In [ ]:
X1

array([-1.90780756e+00, -8.60385011e-01, -4.13605533e-01,  1.88768766e+00,
        5.56553125e-01, -1.33548157e+00,  4.86036289e-01, -1.54730399e+00,
        1.08269105e+00, -4.71124652e-01, -9.36361887e-02,  1.32579665e+00,
       -1.28716357e+00, -1.39711819e+00, -5.83599326e-01,  1.03837885e+00,
       -1.51934608e+00, -2.83215560e+00, -4.51158858e-01,  5.51740800e-01,
        1.20026175e+00, -4.63161362e-01, -4.11426607e-01,  1.15390073e+00,
       -1.86974170e+00, -3.88520775e-01,  1.90423890e-01,  4.49218721e-01,
       -5.09806693e-01,  3.44410117e-02, -2.48832735e+00, -6.58248412e-01,
        4.53508713e-01, -9.82294034e-01,  5.89842216e-02,  4.46872501e-01,
       -3.42549201e-01,  1.70463771e-01, -9.62732565e-01, -2.06611280e-01,
        6.10216170e-01,  1.56972961e-01, -5.86531270e-01,  2.24216404e-01,
        7.14609791e-01, -2.04994128e+00,  1.15907406e+00, -3.36254739e-01,
        4.25489933e-01,  1.19724692e+00, -1.37167370e+00, -7.09441002e-01,
       -2.88548696e-01, -